In [79]:
import pandas as pd

In [80]:
df=pd.read_csv("dirty_sales.csv")

In [81]:
df.head()

,order_id,order_date,customer_name,region,product,category,sales_amount,quantity
0,1,01-01-2024,Amit,Pune,Laptop,Electronics,50000.0,1
1,2,02-01-2024,Neha,Mumbai,Mobile,Electronics,20000.0,2
2,2,02-01-2024,Neha,Mumbai,Mobile,Electronics,20000.0,2
3,3,03-01-2024,Raj,Delhi,Tablet,Electronics,NaN,1
4,4,04-01-2024,Priya,pune,Chair,Furniture,7000.0,3

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       5 non-null      int64
 1   order_date     5 non-null      object
 2   customer_name  5 non-null      object
 3   region         5 non-null      object
 4   product        5 non-null      object
 5   category       5 non-null      object
 6   sales_amount   4 non-null      float64
 7   quantity       5 non-null      int64
dtypes: float64(1), int64(2), object(5)
memory usage: 452.0+ bytes

In [83]:
df.describe()

       order_id  sales_amount  quantity
count  5.000000      4.000000   5.00000
mean   2.400000  24250.000000   1.80000
std    1.140175  18227.726134   0.83666
min    1.000000   7000.000000   1.00000
25%    2.000000  16750.000000   1.00000
50%    2.000000  20000.000000   2.00000
75%    3.000000  27500.000000   2.00000
max    4.000000  50000.000000   3.00000

In [84]:
df.isnull().sum()

order_id         0
order_date       0
customer_name    0
region           0
product          0
category         0
sales_amount     1
quantity         0
dtype: int64

In [85]:
df['sales_amount']=df['sales_amount'].fillna(df['sales_amount'].mean())
print(df)

   order_id  order_date customer_name  region product     category  \
0         1  01-01-2024          Amit    Pune  Laptop  Electronics
1         2  02-01-2024          Neha  Mumbai  Mobile  Electronics
2         2  02-01-2024          Neha  Mumbai  Mobile  Electronics
3         3  03-01-2024           Raj   Delhi  Tablet  Electronics
4         4  04-01-2024         Priya    pune   Chair    Furniture

   sales_amount  quantity
0       50000.0         1
1       20000.0         2
2       20000.0         2
3       24250.0         1
4        7000.0         3

In [86]:
df.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [87]:
df.drop_duplicates()

,order_id,order_date,customer_name,region,product,category,sales_amount,quantity
0,1,01-01-2024,Amit,Pune,Laptop,Electronics,50000.0,1
1,2,02-01-2024,Neha,Mumbai,Mobile,Electronics,20000.0,2
3,3,03-01-2024,Raj,Delhi,Tablet,Electronics,24250.0,1
4,4,04-01-2024,Priya,pune,Chair,Furniture,7000.0,3

In [88]:
df['region']=df['region'].str.title()
print(df)

   order_id  order_date customer_name  region product     category  \
0         1  01-01-2024          Amit    Pune  Laptop  Electronics
1         2  02-01-2024          Neha  Mumbai  Mobile  Electronics
2         2  02-01-2024          Neha  Mumbai  Mobile  Electronics
3         3  03-01-2024           Raj   Delhi  Tablet  Electronics
4         4  04-01-2024         Priya    Pune   Chair    Furniture

   sales_amount  quantity
0       50000.0         1
1       20000.0         2
2       20000.0         2
3       24250.0         1
4        7000.0         3

In [89]:
df.dtypes

order_id           int64
order_date        object
customer_name     object
region            object
product           object
category          object
sales_amount     float64
quantity           int64
dtype: object

In [90]:
df['sales_amount']=df['sales_amount'].astype(int)
print(df)

   order_id  order_date customer_name  region product     category  \
0         1  01-01-2024          Amit    Pune  Laptop  Electronics
1         2  02-01-2024          Neha  Mumbai  Mobile  Electronics
2         2  02-01-2024          Neha  Mumbai  Mobile  Electronics
3         3  03-01-2024           Raj   Delhi  Tablet  Electronics
4         4  04-01-2024         Priya    Pune   Chair    Furniture

   sales_amount  quantity
0         50000         1
1         20000         2
2         20000         2
3         24250         1
4          7000         3

In [91]:
df['bonus']=df['sales_amount']*0.10
print(df)

   order_id  order_date customer_name  region product     category  \
0         1  01-01-2024          Amit    Pune  Laptop  Electronics
1         2  02-01-2024          Neha  Mumbai  Mobile  Electronics
2         2  02-01-2024          Neha  Mumbai  Mobile  Electronics
3         3  03-01-2024           Raj   Delhi  Tablet  Electronics
4         4  04-01-2024         Priya    Pune   Chair    Furniture

   sales_amount  quantity   bonus
0         50000         1  5000.0
1         20000         2  2000.0
2         20000         2  2000.0
3         24250         1  2425.0
4          7000         3   700.0

In [92]:
df.sort_values(by='sales_amount',ascending=False)

,order_id,order_date,customer_name,region,product,category,sales_amount,quantity,bonus
0,1,01-01-2024,Amit,Pune,Laptop,Electronics,50000,1,5000.0
3,3,03-01-2024,Raj,Delhi,Tablet,Electronics,24250,1,2425.0
1,2,02-01-2024,Neha,Mumbai,Mobile,Electronics,20000,2,2000.0
2,2,02-01-2024,Neha,Mumbai,Mobile,Electronics,20000,2,2000.0
4,4,04-01-2024,Priya,Pune,Chair,Furniture,7000,3,700.0

In [93]:
df[df['region']=='Pune']

,order_id,order_date,customer_name,region,product,category,sales_amount,quantity,bonus
0,1,01-01-2024,Amit,Pune,Laptop,Electronics,50000,1,5000.0
4,4,04-01-2024,Priya,Pune,Chair,Furniture,7000,3,700.0

In [94]:
df.groupby('region')['sales_amount'].sum()

region
Delhi     24250
Mumbai    40000
Pune      57000
Name: sales_amount, dtype: int64

In [97]:
df.to_csv('Cleaned_Sales_Data.csv',index=False)