In [2]:
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\Kalyani\DataAnalyst\SixMonths\Day 9 Python_Data_Analysis\sales_data.csv")

In [4]:
df.head()

,order_id,order_date,customer_name,region,product,category,sales_amount,quantity
0,1,01-01-2024,Amit,Pune,Laptop,Electronics,50000,1
1,2,02-01-2024,Neha,Mumbai,Mobile,Electronics,20000,2
2,3,03-01-2024,Raj,Delhi,Tablet,Electronics,15000,1
3,4,04-01-2024,Priya,Pune,Chair,Furniture,7000,3
4,5,05-01-2024,Karan,Mumbai,Desk,Furniture,12000,1

In [5]:
print(df['sales_amount'].sum())

261000

In [38]:
print(df['sales_amount'].mean())

26100.0

In [39]:
print(df['sales_amount'].max())

60000

In [47]:
df[df['region']=='Pune']

,order_id,order_date,customer_name,region,product,category,sales_amount,quantity
0,1,01-01-2024,Amit,Pune,Laptop,Electronics,50000,1
3,4,04-01-2024,Priya,Pune,Chair,Furniture,7000,3
6,7,07-01-2024,Amit,Pune,Mobile,Electronics,18000,1
9,10,10-01-2024,Priya,Pune,Laptop,Electronics,60000,1

In [48]:
df.groupby('region')['sales_amount'].sum()

region
Delhi      85000
Mumbai     41000
Pune      135000
Name: sales_amount, dtype: int64

In [52]:
df.isnull().sum()

order_id         0
order_date       0
customer_name    0
region           0
product          0
category         0
sales_amount     0
quantity         0
dtype: int64

In [53]:
df.dropna()

,order_id,order_date,customer_name,region,product,category,sales_amount,quantity
0,1,01-01-2024,Amit,Pune,Laptop,Electronics,50000,1
1,2,02-01-2024,Neha,Mumbai,Mobile,Electronics,20000,2
2,3,03-01-2024,Raj,Delhi,Tablet,Electronics,15000,1
3,4,04-01-2024,Priya,Pune,Chair,Furniture,7000,3
4,5,05-01-2024,Karan,Mumbai,Desk,Furniture,12000,1
5,6,06-01-2024,Sneha,Delhi,Laptop,Electronics,55000,1
6,7,07-01-2024,Amit,Pune,Mobile,Electronics,18000,1
7,8,08-01-2024,Neha,Mumbai,Chair,Furniture,9000,2
8,9,09-01-2024,Raj,Delhi,Desk,Furniture,15000,1
9,10,10-01-2024,Priya,Pune,Laptop,Electronics,60000,1

In [54]:
df.to_csv("Cleaned_Sales.csv", index=False)